spring.application.name=formauto

# ===== LOGGING CONFIG =====
logging.level.root=INFO
logging.level.com.example.formauto=DEBUG

# ===== CACHE CONFIG =====
spring.thymeleaf.cache=false
spring.web.resources.cache.period=0
